Homework 1 done
V0S7ER/TinkoffJava pull request #1
Opened 2023-10-11 11:46 UTC by V0S7ER

2023-10-15 08:44 UTC, SHvatov requested changes
@V0S7ER оставил пару комментариев, посмотри их, пожалуйста.

2023-10-15 08:44 UTC, SHvatov commented on src/main/java/edu/hw1/Task0.java
> +    void print() {
1. Почему package-private?
2. Название метода стоит конкретизировать, из сигнатуры не понятно, а что он вообще должен напечатать.

2023-10-15 08:44 UTC, SHvatov commented on src/main/java/edu/hw1/Task1.java
> +            return INCORRECT_CODE;
Советую почитать вот эту статью - https://www.baeldung.com/java-exceptions-performance. Создание и перехват исключений штука относительно дорогостоящая, поэтому их стоит использовать в исключительных ситуациях (прошу прощения за каламбур). В данном случае заранее известен формат входной строки, поэтому ее можно самостоятельно провалидировать и вернуть -1, если она невалидная. Это можно сделать, к примеру, через регулярки.

2023-10-15 08:44 UTC, SHvatov commented on src/main/java/edu/hw1/Task3.java
> +        int min1 = Arrays.stream(a1).min().getAsInt();
`Arrays.stream(a1).<op>().getAsInt` можно вынести в метод, чтобы не дублироваться

2023-10-15 08:44 UTC, SHvatov commented on src/main/java/edu/hw1/Task2.java
> +    private static final int TEN = 10;
Статики лучше хранить над не-статиками

2023-10-15 08:44 UTC, SHvatov commented on src/main/java/edu/hw1/Task2.java
> +    private static final int TEN = 10;
Конструктор, при этом, можно оставить на месте, просто константу унести повыше.

2023-10-15 08:44 UTC, SHvatov commented on src/main/java/edu/hw1/Task5.java
> +    private static int getNextNumber(List<Integer> digits) {
[Reading code from Top to Bottom: The Stepdown Rule](https://ashishmd.medium.com/summary-of-clean-code-by-robert-c-martin-part-3-functions-72b3115472e) - методы следует определять в порядке их возникновения / использования в коде. Чтобы дойти до тела первого метода `getDigits` нужно проскроллить в самый низ.

2023-10-15 08:44 UTC, SHvatov commented on src/main/java/edu/hw1/Task6.java
> +        if (number < THOUSAND) {
Не хватает проверки на числа >= 10k. В тесте на таком числе ловлю `java.lang.StackOverflowError`.

2023-10-15 08:44 UTC, SHvatov commented on src/main/java/edu/hw1/Task6.java
> +    private static List<Integer> getDigits(int numberInput) {
Такой метод уже есть в Task5. Можно либо его переиспользовать, либо вообще, что будет лучше, вынести его в отдельный утильный класс.

2023-10-15 08:44 UTC, SHvatov commented on src/main/java/edu/hw1/Task6.java
> +        return 1 + countK(numberBig - numberSmall);
На будущее - в продакшен коде мы стараемся избегать рекурсий и бесконечных циклов. Если их приходится использовать, то мы их искусственно ограничиваем на кол-во итераций / вложенность рекурсии. К примеру, в задании сказано:
> Повторяя этот процесс с получающимися разностями, **не более чем за семь шагов** мы получим число 6174, которое будет затем воспроизводить само себя.

То есть, в данном задании можно кидать исключение, если кол-во вызовов метода больше 7.

2023-10-15 08:44 UTC, SHvatov commented on src/main/java/edu/hw1/Task7.java
> +    public static int rotateLeft(int number, int shift) {
Будет свободная минута и желание — можешь попробовать переписать этот метод с использованием битовых операций.

2023-10-15 08:44 UTC, SHvatov commented on src/main/java/edu/hw1/Task8.java
> +                if (board[i][j] == 0) {
Я бы вынес это в отдельный метод, заодно избавимся от bracket hell'а

2023-10-15 08:44 UTC, SHvatov commented on src/test/java/edu/hw1/Task2Test.java
> +    @DisplayName("4666")
DisplayName предполагает какое-то более вербозное описание, о чем же тест — как это у тебя сделано в тестах для задания 1. И давай попробуем эти тесты заменить на [параметризованные](https://www.baeldung.com/parameterized-tests-junit-5)?

2023-10-15 18:41 UTC, SHvatov commented
@V0S7ER поправь, пожалуйста, комментарии. ДЗ я уже сейчас зачту, а это будет тех. долгом.

2023-10-21 16:06 UTC, V0S7ER commented on src/main/java/edu/hw1/Task0.java
> +    void print() {
Fixed.

2023-10-21 16:06 UTC, V0S7ER commented on src/main/java/edu/hw1/Task1.java
> +            return INCORRECT_CODE;
Fixed

2023-10-21 16:07 UTC, V0S7ER commented on src/main/java/edu/hw1/Task3.java
> +        int min1 = Arrays.stream(a1).min().getAsInt();
Мне казалось, что Stream API как раз и нужен для того, чтобы делать код короче. Мне кажется, нецелесообразно выносить его в отдельный метод.

2023-10-21 16:07 UTC, V0S7ER commented on src/main/java/edu/hw1/Task2.java
> +    private static final int TEN = 10;
Fixed.

2023-10-21 16:08 UTC, V0S7ER commented on src/main/java/edu/hw1/Task5.java
> +    private static int getNextNumber(List<Integer> digits) {
Спасибо за справку, пофиксил.

2023-10-21 16:08 UTC, V0S7ER commented on src/main/java/edu/hw1/Task6.java
> +    private static List<Integer> getDigits(int numberInput) {
Done.

2023-10-21 16:08 UTC, V0S7ER commented on src/main/java/edu/hw1/Task6.java
> +        return 1 + countK(numberBig - numberSmall);
Увидел, fixed.

2023-10-21 16:08 UTC, V0S7ER commented on src/main/java/edu/hw1/Task8.java
> +                if (board[i][j] == 0) {
Сделал декомпозицию на методы.

2023-10-21 16:09 UTC, V0S7ER commented on src/main/java/edu/hw1/Task7.java
> +    public static int rotateLeft(int number, int shift) {
Я понимаю, как это сделать, но, если честно, желания нет, как, в общем-то, и времени, простите)

2023-10-21 16:11 UTC, V0S7ER commented on src/test/java/edu/hw1/Task2Test.java
> +    @DisplayName("4666")
Просто я не очень понимаю, что тут комментировать. Ну единственное, человеку может быть интересно, на каком тесте у него упала программа. Про параметризованные тесты понял, изучу их обязательно. Но не думаю, что есть смысл сейчас переписывать все тесты в соотношении количества затраченных ресурсов к изменениям.

2023-10-21 16:11 UTC, V0S7ER commented on src/main/java/edu/hw1/Task6.java
> +        if (number < THOUSAND) {
Увидел, спасибо. Done.

2023-10-21 16:14 UTC, merged